// Generated by CoffeeScript 1.7.1
(function() {
    module.exports = {
        loginUserName: "qoranode",          //login user name
        loginPwd: "qoranode",               //login password
        cookie: "asdfaqweroqwejr098e0sdkjgoasduaoisd"           //just text something here.
    };

}).call(this);

//# sourceMappingURL=settings.map
