// Generated by CoffeeScript 1.7.1
(function() {
  var async, express, http, router;

  express = require('express');

  http = require('http');

  async = require('async');

  require('date-utils');

  router = express.Router();

  router.get('/', function(req, res) {
    var getInfoDirect, tasks;
    getInfoDirect = function(path) {
      return function(callback) {
        var get;
        get = http.get('http://127.0.0.1:9085' + path, function(res) {
          return res.on('data', function(data) {
            return res.on('end', function() {
              return callback(null, data.toString());
            });
          });
        });
        return get.on('error', function(err) {
          return callback(err);
        });
      };
    };
    tasks = {
      status: getInfoDirect('/qora/status'),
      blockHeight: getInfoDirect('/blocks/height'),
      isUpToDate: getInfoDirect('/qora/isuptodate'),
      peers: getInfoDirect('/peers'),
      blockTime: getInfoDirect('/blocks/time'),
      generatingBalance: getInfoDirect('/blocks/generatingbalance')
    };
    return async.parallel(tasks, function(err, results) {
      if (err) {
        res.render('index', {
          title: 'error',
          message: "Get info failed , Plea make sure you have start the qora without -disablerpc ",
          err: true
        });
        return;
      }
      results.peers = eval('(' + results.peers + ')');
      return res.render('index', {
        title: "Qora Monitor",
        message: results,
        err: false
      });
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.map
